package com.cxx.insert.entity;

import java.io.Serializable;
import java.util.Date;

public class Commodity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.price
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.commodity_id
     *
     * @return the value of t_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.commodity_id
     *
     * @param commodityId the value for t_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.name
     *
     * @return the value of t_commodity.name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.name
     *
     * @param name the value for t_commodity.name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.price
     *
     * @return the value of t_commodity.price
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.price
     *
     * @param price the value for t_commodity.price
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.introduction
     *
     * @return the value of t_commodity.introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.introduction
     *
     * @param introduction the value for t_commodity.introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.create_time
     *
     * @return the value of t_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.create_time
     *
     * @param createTime the value for t_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.update_time
     *
     * @return the value of t_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.update_time
     *
     * @param updateTime the value for t_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}