package com.cxx.insert.entity;

import java.io.Serializable;

public class CommodityDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity_details.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity_details.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity_details.detailed_introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String detailedIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_details
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity_details.id
     *
     * @return the value of t_commodity_details.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity_details.id
     *
     * @param id the value for t_commodity_details.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity_details.commodity_id
     *
     * @return the value of t_commodity_details.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity_details.commodity_id
     *
     * @param commodityId the value for t_commodity_details.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity_details.detailed_introduction
     *
     * @return the value of t_commodity_details.detailed_introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getDetailedIntroduction() {
        return detailedIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity_details.detailed_introduction
     *
     * @param detailedIntroduction the value for t_commodity_details.detailed_introduction
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setDetailedIntroduction(String detailedIntroduction) {
        this.detailedIntroduction = detailedIntroduction;
    }
}