package com.cxx.insert.entity;

import java.io.Serializable;

public class Customers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customers.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customers.customer_name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customers.telephone
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customers.login_no
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String loginNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customers.wechat_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customers.customer_id
     *
     * @return the value of t_customers.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customers.customer_id
     *
     * @param customerId the value for t_customers.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customers.customer_name
     *
     * @return the value of t_customers.customer_name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customers.customer_name
     *
     * @param customerName the value for t_customers.customer_name
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customers.telephone
     *
     * @return the value of t_customers.telephone
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customers.telephone
     *
     * @param telephone the value for t_customers.telephone
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customers.login_no
     *
     * @return the value of t_customers.login_no
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getLoginNo() {
        return loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customers.login_no
     *
     * @param loginNo the value for t_customers.login_no
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setLoginNo(String loginNo) {
        this.loginNo = loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customers.wechat_id
     *
     * @return the value of t_customers.wechat_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customers.wechat_id
     *
     * @param wechatId the value for t_customers.wechat_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }
}