package com.cxx.insert.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderCommodity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_commodity.order_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_commodity.order_id
     *
     * @return the value of t_order_commodity.order_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_commodity.order_id
     *
     * @param orderId the value for t_order_commodity.order_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_commodity.commodity_id
     *
     * @return the value of t_order_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_commodity.commodity_id
     *
     * @param commodityId the value for t_order_commodity.commodity_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_commodity.create_time
     *
     * @return the value of t_order_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_commodity.create_time
     *
     * @param createTime the value for t_order_commodity.create_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_commodity.update_time
     *
     * @return the value of t_order_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_commodity.update_time
     *
     * @param updateTime the value for t_order_commodity.update_time
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}