spring:
  application:
    name: bank-transfer-client
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  scan:
    base-packages: com.dhb.bank.transfer.client
  registry:
    address: zookeeper://192.168.23.162:2181
  metadata-report:
    address: zookeeper://192.168.23.162:2181