package com.cxx.insert.mapper;

import com.cxx.insert.entity.CommodityShippingAddress;
import com.cxx.insert.entity.CommodityShippingAddressExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommodityShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    long countByExample(CommodityShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int deleteByExample(CommodityShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insert(CommodityShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insertSelective(CommodityShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    List<CommodityShippingAddress> selectByExample(CommodityShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExampleSelective(@Param("record") CommodityShippingAddress record, @Param("example") CommodityShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExample(@Param("record") CommodityShippingAddress record, @Param("example") CommodityShippingAddressExample example);
}