package com.cxx.insert.mapper;

import com.cxx.insert.entity.OrderCommodity;
import com.cxx.insert.entity.OrderCommodityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    long countByExample(OrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int deleteByExample(OrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insert(OrderCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insertSelective(OrderCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    List<OrderCommodity> selectByExample(OrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExampleSelective(@Param("record") OrderCommodity record, @Param("example") OrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExample(@Param("record") OrderCommodity record, @Param("example") OrderCommodityExample example);
}