package com.cxx.db.entity;

import java.io.Serializable;

public class CommodityShippingAddress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_shipping_address.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_shipping_address.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_shipping_address.address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer_shipping_address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_shipping_address.id
     *
     * @return the value of t_customer_shipping_address.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_shipping_address.id
     *
     * @param id the value for t_customer_shipping_address.id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_shipping_address.customer_id
     *
     * @return the value of t_customer_shipping_address.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_shipping_address.customer_id
     *
     * @param customerId the value for t_customer_shipping_address.customer_id
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_shipping_address.address
     *
     * @return the value of t_customer_shipping_address.address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_shipping_address.address
     *
     * @param address the value for t_customer_shipping_address.address
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }
}