spring:
  shardingsphere:
    datasource:
      name: admin,slave1,slave2
#      https://www.codeleading.com/article/32595820595/
      common:
        type: com.zaxxer.hikari.HikariDataSource
      admin:
#        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.23.162:3307/homework8?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave1:
#        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    #      这里要改成slave的地址情况
        url: jdbc:mysql://192.168.23.164:3308/homework8?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave2:
#        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #      这里要改成slave的地址情况
        jdbc-url: jdbc:mysql://192.168.23.164:3309/homework8?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ds_ms
      master-data-source-name: admin
      slave-data-source-names: slave1,slave2
    props:
      sql:
        show: true


mybatis:
  type-aliases-package: com.cxx.db.entity
  mapper-locations:
    - classpath*:mapper/*Mapper.xml

server:
  port: 8080