package com.cxx.db.mapper;

import com.cxx.db.entity.Customers;
import com.cxx.db.entity.CustomersExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    long countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int deleteByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExampleSelective(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customers
     *
     * @mbg.generated Fri Apr 15 12:48:50 CST 2022
     */
    int updateByExample(@Param("record") Customers record, @Param("example") CustomersExample example);
}